pre-commit:
  jobs:
    - name: "Run linters & formatters"
      id: group_linters_formatters
      group:
        parallel: true
        jobs:
          - name: "YAML Files"
            id: lint_yaml
            group:
              piped: true
              stage_fixed: true
              jobs:
                - name: "Ensure default config files"
                  run: ruby ./scripts/ensure_config.rb --output .yamllint --input ./scripts/defaults/.yamllint
                - name: "Run yamlfmt"
                  glob: "**/*.{yml,yaml}"
                  run: yamlfmt {staged_files} .yamlfmt --lint
                - name: "Run yamllint"
                  glob: "**/*.{yml,yaml}"
                  run: yamllint {staged_files} .yamllint --strict
