[tools]
lefthook = "1.10.10"
yamlfmt = "0.16.0"
yamllint = "1.35.1"

[tasks.test]
description = "Run tests"
usage = """
arg "[files]" var=#true default="./scripts/**/*.test.ts"
"""
run = 'pnpm run test {{arg(name="files")}}'
