[tools]
lefthook = "1.10.10"
ruby = "3.4.2"
yamlfmt = "0.16.0"
yamllint = "1.35.1"

[tasks.test]
description = "Run tests"
usage = """
arg "[files]" var=#true default="./test/**/*.rb"
"""
run = 'ruby ./test/runner.rb {{arg(name="files")}}'
