[tools]
lefthook = "1.10.10"
node = "22.14.0"
pnpm = "10.4.1"
yamlfmt = "0.16.0"
yamllint = "1.35.1"

[tasks.bootstrap]
description = "Bootstrap the project"

[tasks.test]
description = "Run tests"
usage = """
arg "[files]" var=#true default="./scripts/**/*.test.ts"
"""
run = 'pnpm run test {{arg(name="files")}}'

